name: Build and Package Extensions

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Firefox Extension
        run: |
          mkdir -p ${{ env.FIREFOX_OUTPUT_DIR }}
          cd ${{ env.FIREFOX_EXTENSION_DIR }}
          zip -r ../${{ e